### ISSUE TITLE
Need a way to actually send email

### ISSUE THREAD

**Issue by deniszgonjanin** [boxkite/ckanext-donneesqctheme#21]
Related to #5 

Send using
- Generic SMTP server?
- Existing server?
- Sendgrid/other?

**Comment by Hoedic** [comment]
Until now, I've always used SMTP server since it's not high volume and it's working not that bad thru spam filter (I experienced more issues with spam filters using tool like Sendgrid).

So I would use generic SMTP server if you are ok with that. We have an account with postmark if we want to integrate this later down the road.
