### ISSUE TITLE
Improve organisation page design

### ISSUE THREAD

**Issue by Hoedic** [boxkite/ckanext-donneesqctheme#7]
We want organization to be able to valorized. So the organization page needs some improvements. 

The description and url of the organization and sub-organization (see hierarachical) which are currently in an independant tab should be moved to the organization landing page.

Also would like to add some indicators (like the number of datasets by this organization) and the last updated & most downloaded datasets for this organization.

Overall, the idea is a bit like this (but here is was applied to groups) https://data.hdx.rwlabs.org/group/col

You have a more "narrative" part before jumping to dataset.

The place where I am not sure is: when you go to the following paginations (page2, 3, 4), do we put again the "narrative" part again or do we remove it.

**Comment by deniszgonjanin** [comment]
'Valorize' is my new favourite calque

**Comment by deniszgonjanin** [comment]
@Hoedic http://featuredviews.dcats.ca/ - admin/pass if you want to play with it

This adds a 'featured' checkbox to every Resource View form. For the homepage, I pull in all of the featured views. The same approach could be used to pull in views into each Organization's page, or to set the 'canonical' view to display for each dataset page.

**Comment by deniszgonjanin** [comment]
I've added some code to templates and plugins to expose more information about the organization to the main template instead of hiding it under tabs. 

I expect you have a more clear idea of what exactly the organization page is to look like. I figure a lot of this is design work, so I'll leave it alone for now until the idea crystalizes a bit more.
